server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.115.26.70:3306/db_docshare?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mysql123 #特殊字符需要单引号
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml